version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPMAccessToken" > ./.npmrc
      - npm whoami
      - npm install -g yarn
      - yarn
  build:
    commands:
      - npm run build-prod-min
