version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPMAccessToken" > ~/.npmrc
      - npm whoami
      - npm ci
  build:
    commands:
      - ./build/publish.sh
