name: 'Check Changelog'
description: 'Ensure changelog meets requirements'
inputs:
  pr-body:
    description: 'PR body from the github event'
    required: true
outputs:
  approved-changelog-entry:
    description: 'Changelog entry has passed requirements'
runs:
  using: 'node20'
  main: 'index.js'
