version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16

workflows:
  version: 2
  default:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - collect-stats:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only: main
      - test-flow:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test-unit:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test-render:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test-query:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test-expressions:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - test-browser:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - deploy-hey-pages:
          requires:
            - prepare
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+(-.+)?/
      - deploy-benchmarks:
          requires:
            - lint
            - build
            - test-flow
            - test-unit
            - test-render
            - test-query
            - test-expressions
          filters:
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+(-.+)?/
            branches:
              only:
                - main
                - /release-.*/
      - deploy-release:
          requires:
            - lint
            - build
            - test-flow
            - test-unit
            - test-render
            - test-query
            - test-expressions
          filters:
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+(-.+)?/
            branches:
              ignore: /.*/

defaults: &defaults
  docker:
    - image: circleci/node:10.16-browsers
  working_directory: ~/mapbox-gl-js-internal

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v3-yarn-{{ checksum "yarn.lock" }}
          paths:
            - '~/.yarn'
            - 'node_modules'
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-lint-{{ .Branch }}
            - v2-lint
      - run: yarn run lint
      - run: yarn run lint-docs
      - run: yarn run lint-css
      - save_cache:
          key: v2-lint-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.eslintcache'

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run build-prod-min
      - run: yarn run build-prod
      - run: yarn run build-csp
      - run: yarn run build-dev
      - run: yarn run build-css
      - run: yarn run build-style-spec
      - run: yarn run build-flow-types
      - run: yarn run test-build
      - run:
          name: Check bundle size
          command: |
            node build/check-bundle-size.js
      - deploy:
          name: Trigger memory metrics when merging to main
          command: |
            if [ -n "${WEB_METRICS_TOKEN}" ]; then
              if [[ $CIRCLE_BRANCH == main ]]; then
                curl -X POST https://circleci.com/api/v1.1/project/github/mapbox/web-metrics/build?circle-token=${WEB_METRICS_TOKEN}
              fi
            fi
      - store_artifacts:
          path: "dist"
      - store_artifacts:
          path: "test/release"
      - persist_to_workspace:
          root: .
          paths:
            - dist

  collect-stats:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Collect performance stats
          command: node bench/gl-stats.js
      - aws-cli/install
      - run:
          name: Upload performance stats
          command: aws s3 cp data.json.gz s3://mapbox-loading-dock/raw/gl_js.perf_metrics_staging/ci/`git show -s --date=short --format=%cd-%h HEAD`.json.gz

  test-flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test-flow

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test-unit

  test-render:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run build-token
      - run: yarn run test-render
      - store_test_results:
          path: test/integration/render-tests
      - store_artifacts:
          path: "test/integration/render-tests/index.html"

  test-query:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test-query
      - store_test_results:
          path: test/integration/query-tests
      - store_artifacts:
          path: "test/integration/query-tests/index.html"

  test-browser:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run build-dev
      - run: yarn run build-token
      - run:
          name: Test Chrome
          environment:
            SELENIUM_BROWSER: chrome
            TAP_COLORS: 1
          command: yarn run test-browser
      - run:
          name: Test Firefox
          environment:
            SELENIUM_BROWSER: firefox
            TAP_COLORS: 1
          command: yarn run test-browser

  test-expressions:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn run test-expressions

  deploy-benchmarks:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: BENCHMARK_VERSION="${CIRCLE_TAG:-$CIRCLE_BRANCH} $(git rev-parse --short=7 HEAD)" yarn run build-benchmarks
      - aws-cli/install
      - run:
          name: Upload benchmark
          command: aws s3 cp --acl private --content-type application/javascript bench/versions/benchmarks_generated.js s3://mapbox-gl-js-internal/${CIRCLE_TAG:-$CIRCLE_BRANCH}/benchmarks.js
      - run:
          name: Upload source maps
          command: aws s3 cp --acl private --content-type application/javascript bench/versions/benchmarks_generated.js.map s3://mapbox-gl-js-internal/${CIRCLE_TAG:-$CIRCLE_BRANCH}/benchmarks.js.map

  deploy-hey-pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy hey-pages
          command: |
            # Add ssh host key and setup user config
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
            git config --global user.email "karim.naaji@gmail.com"
            git config --global user.name "karimnaaji"

            # Build new package
            yarn run build-dev
            yarn run build-prod-min
            yarn run build-css
            git checkout hey-pages

            # Update version number and deploy
            sed -i 's|\(MAPBOX_GL_JS_V2_VERSION = \)\(.*\)|\1'"'`git describe --tags $(git rev-list --tags --max-count=1)`'|" index.js

            cp dist/mapbox-gl-dev.js mapbox-gl-dev.js
            cp dist/mapbox-gl.js mapbox-gl.js
            cp dist/mapbox-gl.css mapbox-gl.css
            cp dist/mapbox-gl.js.map mapbox-gl.js.map

            git commit mapbox-gl-dev.js mapbox-gl.js mapbox-gl.js.map mapbox-gl.css index.js -m "Automated update deployment of hey-pages `date`"
            git push origin hey-pages

  deploy-release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - aws-cli/install
      - run:
          name: Deploy release
          command: |
            function upload {
                aws s3 cp --acl private --content-type $2 dist/$1 s3://mapbox-gl-js-internal/$CIRCLE_TAG/$1

                AWS_ACCESS_KEY_ID=$AWSCN_ACCESS_KEY_ID \
                AWS_SECRET_ACCESS_KEY=$AWSCN_SECRET_ACCESS_KEY \
                aws s3 cp --region cn-north-1 --acl private --content-type $2 dist/$1 s3://mapbox-gl-js-internal-cn-north-1/$CIRCLE_TAG/$1
            }

            upload mapbox-gl.js     application/javascript
            upload mapbox-gl.js.map application/octet-stream
            upload mapbox-gl-dev.js application/javascript
            upload mapbox-gl.css    text/css

            upload mapbox-gl-unminified.js     application/javascript
            upload mapbox-gl-unminified.js.map application/octet-stream
            upload mapbox-gl-csp.js            application/javascript
            upload mapbox-gl-csp.js.map        application/octet-stream
            upload mapbox-gl-csp-worker.js     application/javascript
            upload mapbox-gl-csp-worker.js.map application/octet-stream
