version: 2

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+(-.+)?/
            branches:
              ignore: /.*/

defaults: &defaults
    docker:
      - image: mbgl/ci:r4-linux-gl-js
    working_directory: ~/mapbox-gl-js

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn
      - restore_cache:
          keys:
            - v1-lint-{{ .Branch }}
            - v1-lint
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - '~/.yarn'
            - 'node_modules'
      - run:
          name: run tests
          command: |
            bash ./.circleci/test.sh
      - save_cache:
          key: v1-lint-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.eslintcache'
      - store_artifacts:
          path: "test/integration/render-tests/index.html"
      - store_artifacts:
          path: "test/integration/query-tests/index.html"
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: bash ./.circleci/deploy.sh
