version: 2

jobs:
  build:
    docker:
      - image: mbgl/ci:r4-linux-gl-js
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - restore_cache:
          key: v1-mapbox-gl-js-cache
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: v1-mapbox-gl-js-cache
          paths:
            - '~/.yarn'
            - '.eslintcache'
            - 'node_modules'
      - run:
          name: run tests
          command: |
            bash ./.circleci/test.sh
      - store_artifacts:
          path: "test/integration/render-tests/index.html"
      - store_artifacts:
          path: "test/integration/query-tests/index.html"
      - run:
          name: deploy if tagged
          when: on_success
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\-dev)/
            branches:
              ignore: /.*/
          command: bash ./.circleci/deploy.sh
